language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "2.5"
  - "2.4"
  - "2.3"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
 - pip install lxml
# command to run tests, e.g. python setup.py test
script:  
 - python setup.py test
notifications:
  email: false
